### ISSUE TITLE
Bug in _get_poi

### ISSUE THREAD

**Issue by SpontaneousDuck** [mroftei/TerrainGeneration#15]
_get_poi can still generate out of bound results.
Inputs to _estimate_path_gain() and result of _get_poi()  
![image](https://github.com/user-attachments/assets/4e2a8855-6eb5-44ac-8d9e-3ff333fb774a)

**Comment by SpontaneousDuck** [comment]
Also produces error after fix:
![image](https://github.com/user-attachments/assets/df6cae27-3566-44f1-8de8-0e8aeec7c7b3)

**Comment by nishanthmarer** [comment]
Issue fixed. 

It turns out that the line

distance_path = torch.cdist(tx_xyz, rx_xyz, p=2)

was calculating the 3D distance and not the 2D distance as we need.

This was causing the distance_ratio to be scaled down by a random factor and causing the points not go outside the map even though we have specified the distance between the Tx and the new point must be greater than the diagonal length of the map

new fix:
distance_path = torch.cdist(tx_xyz[...,:2], rx_xyz[...,:2], p=2)

Manually verified the math, it checks out
